# fly.toml app configuration file generated for web-speed-hackathon-2024-kixflq on 2025-02-23T14:28:59Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'web-speed-hackathon-2024-kixflq'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
